### PR TITLE
Fix Komoju additional capture

### PR DESCRIPTION
**Pull request by shioyama**
So a spree payment `amount` is not a `Spree::Money`, but instead a
`BigDecimal`... you can't take `cents` from that.

Actually what we need to do is get `payment.money`, defined
[here](https://github.com/degica/liquidus/blob/51e573ee78383213e6abef6c0291ca1e00c4d9bd/core/app/models/spree/payment.rb#L72),
and take `cents` on *that*.

Pretty confusing...

### CODE REVIEW

**Comment by degicat** [comment]
@degicat Please review this.

**Comment by degicat** [comment]
@rramsden Please review this.

**Comment by rramsden** [comment]
LGTM

**Comment by shioyama** [comment]
Refs:

https://github.com/degica/liquidus/blob/51e573ee78383213e6abef6c0291ca1e00c4d9bd/core/app/models/spree/payment/processing.rb#L44

**Pull request merged**
